name: 'Hexo_GitHub_Deploy_Action'
description: 'A GitHub action used to automatic generate and deploy hexo-based blog.'
author: 'yrpang'
branding:
  icon: upload-cloud
  color: green
inputs:
  deploykey:
    description: 'The develop key of your GitHub Page repository'
    required: true
  username:
    description: "The publisher's username"
    required: false
    default: 'github-actions[bot]'
  email:
    description: "The publisher's email address"
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'
  if_keep_commit_history:
    description: 'Whether keep commit history'
    required: false
    default: false
  github_page_repository:
    description: >
      When `if_keep_commit_history` is `ture` and the GitHub Page repository (branch) is not `<actor_username>.github.io`, you need to set the other GitHub Page repository (branch) for get the commit history.
    required: false
  github_page_repository_branch:
    description: >
      When `if_keep_commit_history` is `ture` and the GitHub Page repository (branch) is not `<actor_username>.github.io`, you need to set the other GitHub Page repository (branch) for get the commit history.
    required: false
    default: 'master'
  if_update_files:
    description: 'Whether update the source file after generate'
    required: false
    default: false
  github_token:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: false
    default: ''
  branch:
    description: 'The branch of the blog source code'
    required: false
    default: 'master'
  if_update_cloudflare:
    description: 'Whether update cloudflare'
    required: false
    default: false
  cloudflare_token: 
    description: 'Your cloudflare api key'
    required: false
  cloudflare_zone:
    description: 'the cloudflare zone'
    required: false
  cloudflare_username:
    description: 'Your cloudflare user name'
    required: false
  purge_list:
    description: 'purge list'
    required: false
  
runs:
  using: 'docker'
  image: 'Dockerfile'
